### ISSUE TITLE
fried img not downloaded

### ISSUE THREAD

**Issue by JackyChiu** [Tricktionary/TheFry#3]
download button downloads the original image instead of the fried one
@Tricktionary

**Comment by Tricktionary** [comment]
@JackyChiu What web browser and OS ?

**Comment by Tricktionary** [comment]
Is the image corrupted ?

**Comment by JackyChiu** [comment]
@Tricktionary 
> @JackyChiu What web browser and OS ?

macOS, Firefox. I think it's a regression because it worked before on Firefox. 

> Is the image corrupted ?

The image is just the orignal image uploaded.
